package com.ms.PROJECTSERVICE.pojo;
// Generated 23 Nov, 2024 3:14:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "hrdept")
public class Emp implements java.io.Serializable {

	private Integer empid;
	private Acct acct;
	private Address address;
	private Project project;
	private String name;
	private Set<Project> projects = new HashSet<Project>(0);

	public Emp() {
	}

	public Emp(Acct acct, Address address, Project project, String name, Set<Project> projects) {
		this.acct = acct;
		this.address = address;
		this.project = project;
		this.name = name;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "empid", unique = true, nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acct_id")
	public Acct getAcct() {
		return this.acct;
	}

	public void setAcct(Acct acct) {
		this.acct = acct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emp")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
